### ISSUE TITLE
Gali and Kopaka's boss doors imporperly render their textures

### ISSUE THREAD

**Issue by robot5431** [TheLegendOfMataNui/game-issues#103]
While Onua, Pohatu, and Tahu's boss doors have a ripply color effect on the image of the boss, Gali's door is missing the ripple effect and only displays the boss image. Kopaka's door, on the other hand, is missing its texture entirely, and is just a white translucent square.

Proper Example (it's the purple part, kind of hard to see with a still image):
![bandicam 2018-03-31 16-52-27-437](https://user-images.githubusercontent.com/37253627/38167921-e4a2ff3c-3504-11e8-8cb5-de8cc2f172f1.jpg)

Gali's door:
![bandicam 2018-03-31 16-53-56-505](https://user-images.githubusercontent.com/37253627/38167926-f4460592-3504-11e8-93fb-2d9ec132d41c.jpg)

Kopaka's door:
![bandicam 2018-03-31 16-56-32-037](https://user-images.githubusercontent.com/37253627/38167930-fd809884-3504-11e8-9534-c7c9e53eab4d.jpg)

**Comment by ShadowOfNight** [comment]
Both issues were resolved in the beta.  The Gali boss door is because of the dummied out texture slb it was using, and Kopaka's boss door due to the fact it was missing texture.  Issue closed.

**Comment by ShadowOfNight** [comment]
Fixed now.  Gali's boss door was inadvertently broken by the texture slb made by Vahkiti.  

Kopaka's boss door is lacking textures altogether; fixed by back-porting the textures from the beta build.
An entry needed to be added to the texture slb for Kopaka's level in order for the boss door to animate, but this is fixed and will remain closed.
