### ISSUE TITLE
Onua falls through Gali's first area upon transitioning from Onua's elemental boss

### ISSUE THREAD

**Issue by Expack3** [TheLegendOfMataNui/game-issues#127]
**Summary:**
When playing the game through the frontend, beating Onua's elemental boss and going through the transition area revealed after the boss battle, the first Toa falls from the top of the first area of Gali to its bottom, resulting in a crash.

**Build Version:**
"Beta" October 23, 2001

**Steps to Reproduce:**

1. Replace the dgVoodoo2 DLLs with the [latest stable](http://dege.freeweb.hu/dgVoodoo2/dgVoodoo2.html) (2.55 as of this posting)
2. Copy-paste the contents of dgVoodoo.conf with [this.](https://gist.github.com/Expack3/5964ed66ded09e1e0f3ee15475faaead)
3. Start a new game from the frontend as Player 2.
4. Get the grappling hook.
5. Free the village.
6. Talk to the villager missing a drill.

7. Get the missing drill and return it to its villager, collecting the reward.

8. Talk to the villager missing a spin disc.

9. Get the spin disc, then go to the central hub.

10. Talk to the NPC at the central hub.

10. From the central hub, return to the first village, give the spin disc to its villager, and collect the reward.

11. Fight the elemental boss and win.
12. Go to the transition area opened up after the boss fight.

**Comment by R3-T7** [comment]
I am having the exact same problem.

**Comment by ivanproff** [comment]
Same.

**Comment by ShadowOfNight** [comment]
This is because running the game from Front End disables all in-engine cutscenes.  The start of this particular one also triggers a character swap, which explains why you see Onua falling.  On top of this, the spawn positions are way off the mark, which explains why you show up so far out of the map.  The cutscene that triggers (Onua meets Gali) places you back in the map properly after it finishes, but it will crash a few moments later.  

I fixed the positioning problem, but the area lacks a trigger to make the door function, meaning you'll need to use the debug menu to warp out of there.  

Edit: the crash is a different problem altogether, not cutscene related.

**Comment by ShadowOfNight** [comment]
Because the falling out of world issue will be resolved in the patch, and because the front end disabling cutscenes is a different issue, I am closing and marking as resolved.
