### ISSUE TITLE
Stone Elemental crash

### ISSUE THREAD

**Issue by ShadowOfNight** [TheLegendOfMataNui/game-issues#178]
Attempting to hit the stone elemental with an elemental sphere at any range other than point blank results in a crash.
Address: 0047b40f

**Comment by OndrikB** [comment]
This is also the same address at which it crashes when setting a different boss's health to a negative value. Presumably it crashes while trying to remove the dots, and this specific crash is caused by the elemental sphere subtracting one from the health for every frame that it's inside the stone elemental's hitbox.

**Comment by ShadowOfNight** [comment]
@JrMasterModelBuilder Patched the exe to prevent the crash, though we are still left with the problem of the spheres killing it instantly.  Closing this issue.
