### ISSUE TITLE
Invisible moving platforms in Kopaka's CRSS and PATH are broken

### ISSUE THREAD

**Issue by ReeseWB-001** [TheLegendOfMataNui/game-issues#184]
Video example of it working properly: https://youtu.be/WAFEa-t1S1E
The invisible platforms in Kopaka's level are barely functional. On very rare occasions (once in a blue moon, as far as I'm concerned), they'll work as intended. The only example of the platform in PATH moving is the video above, recorded on my Win8 laptop (and even then, it doesn't always work like that for me). However, for a majority of the time, they will either
a.) Not move at all or
b.) Jitter forwards for a moment before stopping.
Additionally, there is a decent chance that Kopaka will simply clip into the platforms, unable to escape.

![clipping](https://user-images.githubusercontent.com/37253627/41952358-13e683b6-7995-11e8-8762-33d877ab36a9.png)
(Image courtesy of Vahkiti, project lead)

**Comment by ReeseWB-001** [comment]
UPDATE: There has been one reported case of this working on Win10.
Additionally, the CRSS platforms and the PATH platform breaking are not mutually exclusive. If one map is broken, the other is. If one works, the other works.

**Comment by OndrikB** [comment]
This got apparently fixed in the latest patch, although more testing is required.

**Comment by ReeseWB-001** [comment]
This issue is tied to FPS. At 30, the platforms work fine.

**Comment by ShadowOfNight** [comment]
This was identified as being due to Saffire making the platforms function at 40fps and below in the script class for them.  

The class in question has been reworked, thus completely removing framerate dependency.  This issue was patched with a small hack originally but has now been properly and permanently resolved.  Fix will be included in next Alpha, Legacy, and Rebuilt patches.
