### ISSUE TITLE
The hitboxes of the Fikou-Nui and Nui-Jaga minibosses are too small

### ISSUE THREAD

**Issue by OndrikB** [TheLegendOfMataNui/game-issues#240]

**Comment by Vahkiti** [comment]
Fikou Nui's hitbox will be fixed in the next patch. Nui Jaga's will be larger, but due to its model being offset from its own origin, it will be in a slightly incorrect position. Will require [BHD generation](https://github.com/TheLegendOfMataNui/game-issues/issues/228) from @epicabsol to address further.

**Comment by ShadowOfNight** [comment]
This will be addressed in Rebuilt 1.1.  Closing issue
