### ISSUE TITLE
Unable to progress beyond Ga-koro in Gali's level

### ISSUE THREAD

**Issue by PootisBear** [TheLegendOfMataNui/game-issues#299]
I found this issue to occur in rebuilt V1.1 

In Gali's level after entering Ga-Koro and destroying the two rahi and their nests, the trigger for saving the village never seems to occur and likewise the music doesn't change. Nokama's hut remains closed off and there's no way to gain access inside or otherwise make the other tohunga appear as intended.  Heading back to the initial starting area and then into Ga-Koro again respawns the rahi but killing them again makes no difference. The grappling hook and kanohi rau are obtainable as normal however the token door in Ga-Koro does not open even upon meeting the requirements of possessing the rau and 14+ tokens,  therefore making it impossible to progress any further in the level.

**Comment by ShadowOfNight** [comment]
There are 2 hives in the underwater section of the village, one spawns sharks the other spawns piranhas.  You'll need to destroy those as well, but based on what you've described this is behaving as intended due to you only destroying the 2 hives on land.  If you still encounter this issue after destroying all 4 hives and freeing the Rahi that spawn from them, then there's an issue here.

Might be looking into a way to telegraph there are additional hives in the area.
