### ISSUE TITLE
Stuck in Gali underwater level

### ISSUE THREAD

**Issue by Karambat** [TheLegendOfMataNui/game-issues#305]
Rebuilt most recent version as of August 8th, 2023

During the underwater section of Gali's level, where you have to press several buttons to unlock a door, the door won't open no matter in what order the buttons are pressed. I tried to see if I missed any, but that doesn't seem to be the case, so after pressing all the buttons, the door remains closed.

**Comment by ShadowOfNight** [comment]
@Karambat 
This is a known issue we had noticed internally.  One of the buttons will appear to be pressed down already but it is not.  Make sure to try to press that one as well; this should allow you to continue.

The button in question has been fixed and will be part of the next release.  Due to this, I am closing the ticket.  
Thank you for your report!
